# Generated by Django 4.2.2 on 2025-06-18 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
