# Generated by Django 4.2.2 on 2025-06-18 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_entry_title_alter_entry_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
