# Generated by Django 4.2.2 on 2025-06-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0003_remove_entry_tags_delete_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Заголовок"
            ),
        ),
    ]
