# Generated by Django 4.2.2 on 2025-06-18 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diary", "0004_alter_entry_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="entry",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
    ]
